/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandingRouteImport } from './routes/standing'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as DivisionsRouteImport } from './routes/divisions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const StandingRoute = StandingRouteImport.update({
  id: '/standing',
  path: '/standing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsRoute = DivisionsRouteImport.update({
  id: '/divisions',
  path: '/divisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/divisions': typeof DivisionsRoute
  '/highlights': typeof HighlightsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/standing': typeof StandingRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/divisions': typeof DivisionsRoute
  '/highlights': typeof HighlightsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/standing': typeof StandingRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/divisions': typeof DivisionsRoute
  '/highlights': typeof HighlightsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/standing': typeof StandingRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/divisions'
    | '/highlights'
    | '/news'
    | '/register'
    | '/schedule'
    | '/standing'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/divisions'
    | '/highlights'
    | '/news'
    | '/register'
    | '/schedule'
    | '/standing'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/divisions'
    | '/highlights'
    | '/news'
    | '/register'
    | '/schedule'
    | '/standing'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DivisionsRoute: typeof DivisionsRoute
  HighlightsRoute: typeof HighlightsRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  StandingRoute: typeof StandingRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standing': {
      id: '/standing'
      path: '/standing'
      fullPath: '/standing'
      preLoaderRoute: typeof StandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions': {
      id: '/divisions'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof DivisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DivisionsRoute: DivisionsRoute,
  HighlightsRoute: HighlightsRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  StandingRoute: StandingRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
